# The advisory gate: every crate in Cargo.lock (including the bundled
# sqlite and the vendored lua build) is checked against the RustSec
# advisories database in CI. Only the advisories check is gated; the
# other cargo-deny checks (licenses/bans/sources) are deliberately not
# part of this repo's gate.
[advisories]
version = 2
yanked = "deny"
